### ISSUE TITLE
androidmanifest.xml could not be found

### ISSUE THREAD

**Issue by samadtalukder** [squadhead/IUBian-Student-Companion#1]
I pulled your project and build this project then show this message in below:

AndroidManifest.xml could not be found.
Please check E:\IUBian-Student-Companion\android\AndroidManifest.xml for errors.
No application found for TargetPlatform.android_x86.
Is your project missing an android\AndroidManifest.xml?
Consider running "flutter create ." to create one.

**Comment by rikousik** [comment]
Steps to resolve this problem: 
1) delete android folder from project directory,
2) open terminal (cd project directory) -> run: flutter create . 
(don't forget the dot '.' )

**Comment by samadtalukder** [comment]
I followed your steps but I faced a problem. That's I share with you.

1. Firstly I deleted my android folder from my project directory
2. Opened my terminal wrote which you called me. 
3. **$ flutter create .**

After writing this command then they show me an error.

> "IUBian-Student-Companion" is not a valid Dart package name.
> 
> See https://dart.dev/tools/pub/pubspec#name for more information.

After getting this error I copy the project name from pubsec.yaml file and wrote new command is 
**$ flutter create iub_student_companion**

This way I solve my problem. Thank you

**Comment by rikousik** [comment]
> I followed your steps but I faced a problem. That's I share with you.
> 
>     1. Firstly I deleted my android folder from my project directory
> 
>     2. Opened my terminal wrote which you called me.
> 
>     3. **$ flutter create .**
> 
> 
> After writing this command then they show me an error.
> 
> > "IUBian-Student-Companion" is not a valid Dart package name.
> > See https://dart.dev/tools/pub/pubspec#name for more information.
> 
> After getting this error I copy the project name from pubsec.yaml file and wrote new command is
> **$ flutter create iub_student_companion**
> 
> This way I solve my problem. Thank you

smart , glad you're able to run it after all
